import{i as u}from"./assets/vendor-8e8cd629.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="https://pixabay.com",d="44423269-f21c5bc9414954348df27e7dd";function m(n){const o="/api/",r=new URLSearchParams({key:d,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0}),s=`${f}${o}?${r}`;return fetch(s).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).catch(e=>{console.error("Error fetching images:",e)})}function p(n){const o=document.getElementById("gallery");o.innerHTML=n.map(r=>`
      <a href="${r.largeImageURL}" data-lightbox="gallery">
        <div class="image-card">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <p>${r.tags}</p>
        </div>
      </a>
    `).join(""),lightbox.refresh()}function c(n){u.error({title:"Error",message:n})}const a=document.querySelector(".loader-wrapper"),l={form:document.querySelector(".js-picture-form"),input:document.querySelector('.js-picture-form input[name="query"]'),gallery:document.getElementById("gallery")};l.form.addEventListener("submit",function(n){n.preventDefault();const o=l.input.value.trim();if(o===""){c("Please enter a search term");return}a.style.display="block",m(o).then(r=>{a.style.display="none",r.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):p(r.hits)}).catch(r=>{a.style.display="none",c("An error occurred while fetching the images. Please try again.")})});
//# sourceMappingURL=commonHelpers.js.map
